language: cpp
dist: trusty

# Install newer version of CMake as the one that comes preinstalled on
# travis-ci doesn't support CMakeAddFortranSubdirectory.
before_install:
  - sudo apt-get update
  - sudo apt-get install libc6:i386
  - wget --no-check-certificate http://www.cmake.org/files/v3.6/cmake-3.6.3-Linux-i386.tar.gz

install:
  - tar xzf cmake-3.6.3-Linux-i386.tar.gz
  - sudo apt-get install gfortran

script:
  - cmake-3.6.3-Linux-i386/bin/cmake .
  - make -j3
  - make test
